from typing import Protocol

from proextractor.domain.models import Song, SongSearchResult, SongSummary


class SongRepository(Protocol):
    def save_song(self, song: Song) -> int: ...
    def list_songs(self) -> list[SongSummary]: ...
    def search(self, query: str) -> list[SongSearchResult]: ...
    def get_song(self, identifier: str | int) -> Song: ...

